In [1]:
import numpy as np

# 逻辑运算

In [2]:
score = np.random.randint(40, 100, (10, 5))

In [3]:
score

array([[89, 56, 51, 79, 91],
       [66, 95, 57, 50, 58],
       [44, 88, 79, 83, 74],
       [76, 71, 44, 65, 44],
       [96, 45, 45, 91, 76],
       [53, 52, 54, 90, 70],
       [97, 50, 73, 48, 50],
       [90, 46, 60, 71, 44],
       [94, 40, 52, 41, 73],
       [96, 95, 68, 69, 47]])

In [4]:
test_score = score[6:, 0:5]

In [5]:
test_score

array([[97, 50, 73, 48, 50],
       [90, 46, 60, 71, 44],
       [94, 40, 52, 41, 73],
       [96, 95, 68, 69, 47]])

In [6]:
test_score > 60

array([[ True, False,  True, False, False],
       [ True, False, False,  True, False],
       [ True, False, False, False,  True],
       [ True,  True,  True,  True, False]])

In [7]:
test_score[test_score > 60] = 1

In [8]:
test_score

array([[ 1, 50,  1, 48, 50],
       [ 1, 46, 60,  1, 44],
       [ 1, 40, 52, 41,  1],
       [ 1,  1,  1,  1, 47]])

# 通用判断函数

In [9]:
np.all(score[0:2, :] > 60)

False

In [10]:
score

array([[89, 56, 51, 79, 91],
       [66, 95, 57, 50, 58],
       [44, 88, 79, 83, 74],
       [76, 71, 44, 65, 44],
       [96, 45, 45, 91, 76],
       [53, 52, 54, 90, 70],
       [ 1, 50,  1, 48, 50],
       [ 1, 46, 60,  1, 44],
       [ 1, 40, 52, 41,  1],
       [ 1,  1,  1,  1, 47]])

In [11]:
np.any(score[0:2, :] > 90)

True

# np.where（三元运算符）

In [12]:
temp = score[:4, :4]

In [13]:
temp

array([[89, 56, 51, 79],
       [66, 95, 57, 50],
       [44, 88, 79, 83],
       [76, 71, 44, 65]])

In [14]:
np.where(temp > 60, 1, 0)

array([[1, 0, 0, 1],
       [1, 1, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1]])

In [16]:
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

array([[1, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 1, 0, 1]])

In [17]:
np.where(np.logical_or(temp > 90, temp < 60), 1, 0)

array([[0, 1, 1, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [0, 0, 1, 0]])

# 统计运算

In [18]:
temp = score[:4, :]

In [19]:
temp

array([[89, 56, 51, 79, 91],
       [66, 95, 57, 50, 58],
       [44, 88, 79, 83, 74],
       [76, 71, 44, 65, 44]])

In [20]:
np.max(temp)

95

In [22]:
np.mean(temp)

68.0

In [23]:
np.max(temp, axis=0)

array([89, 95, 79, 83, 91])

In [24]:
np.max(temp, axis=1)

array([91, 95, 88, 76])

In [25]:
np.argmax(temp)

6

In [26]:
np.argmax(temp, axis=0)

array([0, 1, 2, 2, 0])

In [27]:
np.argmin(temp, axis=0)

array([2, 0, 3, 1, 3])

# 数组间的运算

In [28]:
a = np.array([[1,2,3],[3,4,5]])

In [29]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [30]:
a + 3

array([[4, 5, 6],
       [6, 7, 8]])

In [31]:
a / 2

array([[0.5, 1. , 1.5],
       [1.5, 2. , 2.5]])

In [32]:
a = [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [33]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [35]:
# arr1 + arr2 # 不可以进行计算

In [36]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [37]:
arr1.shape

(2, 6)

In [38]:
arr2.shape

(2, 1)

In [39]:
arr2+arr1

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

# 矩阵运算

In [3]:
a = np.array([[80, 86],
[82, 80],
[85, 78],
[90, 90],
[86, 82],
[82, 90],
[78, 80],
[92, 94]])

In [4]:
a

array([[80, 86],
       [82, 80],
       [85, 78],
       [90, 90],
       [86, 82],
       [82, 90],
       [78, 80],
       [92, 94]])

In [5]:
b = np.array([[0.7], [0.3]])

In [6]:
b

array([[0.7],
       [0.3]])

In [7]:
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [8]:
np.matmul(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [9]:
c = 10

In [10]:
np.dot(c, a)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [12]:
# np.matmul(c, a)  # matmul不支持矩阵和标量的乘法