# series
## series的创建

In [2]:
import pandas as pd
import numpy as np

In [4]:
pd.Series(np.arange(9))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
dtype: int64

In [5]:
pd.Series([1.2, 2.3, 4.5, 5.0], index=[1, 2, 3, 4])

1    1.2
2    2.3
3    4.5
4    5.0
dtype: float64

In [8]:
color_count = pd.Series({"red":10, "green":20, "blue":100})

In [9]:
color_count

blue     100
green     20
red       10
dtype: int64

## series的属性

In [10]:
color_count.index

Index(['blue', 'green', 'red'], dtype='object')

In [11]:
color_count.values

array([100,  20,  10])

In [12]:
color_count[0]

100

In [13]:
color_count[1]

20

# DataFrame
## DataFrame创建

In [14]:
pd.DataFrame(np.random.randn(2,3))

0         1         2
0  1.434003  0.715434 -1.066398
1  0.069269 -0.477732 -0.911352

In [15]:
score = np.random.randint(40, 100, (10, 5))

In [16]:
score

array([[98, 85, 84, 93, 83],
       [73, 68, 64, 47, 87],
       [91, 58, 86, 92, 46],
       [62, 86, 99, 75, 66],
       [49, 73, 46, 61, 81],
       [43, 96, 47, 65, 90],
       [98, 84, 60, 73, 54],
       [59, 93, 58, 83, 43],
       [62, 66, 51, 88, 89],
       [66, 60, 63, 57, 51]])

In [17]:
score_df = pd.DataFrame(score)

In [18]:
score_df

0   1   2   3   4
0  98  85  84  93  83
1  73  68  64  47  87
2  91  58  86  92  46
3  62  86  99  75  66
4  49  73  46  61  81
5  43  96  47  65  90
6  98  84  60  73  54
7  59  93  58  83  43
8  62  66  51  88  89
9  66  60  63  57  51

In [21]:
subjects = ["语文", "数学", "英语", "政治", "体育"]

stu = ["同学"+ str(i) for i in range(score_df.shape[0])]

data = pd.DataFrame(score, columns=subjects, index=stu)

In [20]:
stu

['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9']

In [22]:
data

语文  数学  英语  政治  体育
同学0  98  85  84  93  83
同学1  73  68  64  47  87
同学2  91  58  86  92  46
同学3  62  86  99  75  66
同学4  49  73  46  61  81
同学5  43  96  47  65  90
同学6  98  84  60  73  54
同学7  59  93  58  83  43
同学8  62  66  51  88  89
同学9  66  60  63  57  51

## DataFrame的属性

In [23]:
data.shape

(10, 5)

In [24]:
data.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [25]:
data.columns

Index(['语文', '数学', '英语', '政治', '体育'], dtype='object')

In [26]:
data.values

array([[98, 85, 84, 93, 83],
       [73, 68, 64, 47, 87],
       [91, 58, 86, 92, 46],
       [62, 86, 99, 75, 66],
       [49, 73, 46, 61, 81],
       [43, 96, 47, 65, 90],
       [98, 84, 60, 73, 54],
       [59, 93, 58, 83, 43],
       [62, 66, 51, 88, 89],
       [66, 60, 63, 57, 51]])

In [27]:
data.T

同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   98   73   91   62   49   43   98   59   62   66
数学   85   68   58   86   73   96   84   93   66   60
英语   84   64   86   99   46   47   60   58   51   63
政治   93   47   92   75   61   65   73   83   88   57
体育   83   87   46   66   81   90   54   43   89   51

In [29]:
data

语文  数学  英语  政治  体育
同学0  98  85  84  93  83
同学1  73  68  64  47  87
同学2  91  58  86  92  46
同学3  62  86  99  75  66
同学4  49  73  46  61  81
同学5  43  96  47  65  90
同学6  98  84  60  73  54
同学7  59  93  58  83  43
同学8  62  66  51  88  89
同学9  66  60  63  57  51

In [28]:
data.head()

语文  数学  英语  政治  体育
同学0  98  85  84  93  83
同学1  73  68  64  47  87
同学2  91  58  86  92  46
同学3  62  86  99  75  66
同学4  49  73  46  61  81

In [30]:
data.head(3)

语文  数学  英语  政治  体育
同学0  98  85  84  93  83
同学1  73  68  64  47  87
同学2  91  58  86  92  46

In [31]:
data.tail(3)

语文  数学  英语  政治  体育
同学7  59  93  58  83  43
同学8  62  66  51  88  89
同学9  66  60  63  57  51

## DataFrame索引值的设置

In [35]:
stu = ["同学_"+ str(i) for i in range(score_df.shape[0])]

data.index = stu

In [36]:
# stu

In [37]:
data

语文  数学  英语  政治  体育
同学_0  98  85  84  93  83
同学_1  73  68  64  47  87
同学_2  91  58  86  92  46
同学_3  62  86  99  75  66
同学_4  49  73  46  61  81
同学_5  43  96  47  65  90
同学_6  98  84  60  73  54
同学_7  59  93  58  83  43
同学_8  62  66  51  88  89
同学_9  66  60  63  57  51

In [39]:
# data.index[2] = "同学__"

In [40]:
data.reset_index()

index  语文  数学  英语  政治  体育
0  同学_0  98  85  84  93  83
1  同学_1  73  68  64  47  87
2  同学_2  91  58  86  92  46
3  同学_3  62  86  99  75  66
4  同学_4  49  73  46  61  81
5  同学_5  43  96  47  65  90
6  同学_6  98  84  60  73  54
7  同学_7  59  93  58  83  43
8  同学_8  62  66  51  88  89
9  同学_9  66  60  63  57  51

In [41]:
data.reset_index(drop=True)

语文  数学  英语  政治  体育
0  98  85  84  93  83
1  73  68  64  47  87
2  91  58  86  92  46
3  62  86  99  75  66
4  49  73  46  61  81
5  43  96  47  65  90
6  98  84  60  73  54
7  59  93  58  83  43
8  62  66  51  88  89
9  66  60  63  57  51

In [42]:
df = pd.DataFrame({'month': [1, 4, 7, 10],
                    'year': [2012, 2014, 2013, 2014],
                    'sale':[55, 40, 84, 31]})

In [43]:
df

month  sale  year
0      1    55  2012
1      4    40  2014
2      7    84  2013
3     10    31  2014

In [44]:
df.set_index("year")

month  sale
year             
2012      1    55
2014      4    40
2013      7    84
2014     10    31

In [46]:
df = df.set_index(["year", "month"])

In [47]:
df

sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

# MultiIndex与Panel
## MultiIndex

In [48]:
df

sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

In [49]:
df.index

MultiIndex(levels=[[2012, 2013, 2014], [1, 4, 7, 10]],
           labels=[[0, 2, 1, 2], [0, 1, 2, 3]],
           names=['year', 'month'])

In [50]:
df.index.names

FrozenList(['year', 'month'])

In [51]:
df.index.levels

FrozenList([[2012, 2013, 2014], [1, 4, 7, 10]])

In [53]:
arrays = [[1, 1, 2, 2], ["r", "b", "r","b"]]
pd.MultiIndex.from_arrays(arrays, names=("num", "col"))

MultiIndex(levels=[[1, 2], ['b', 'r']],
           labels=[[0, 0, 1, 1], [1, 0, 1, 0]],
           names=['num', 'col'])

## panel

In [54]:
p = pd.Panel(data=np.arange(24).reshape(4,3,2),
                 items=list('ABCD'),
                 major_axis=pd.date_range('20130101', periods=3),
                 minor_axis=['first', 'second'])

In [55]:
p

<class 'pandas.core.panel.Panel'>
Dimensions: 4 (items) x 3 (major_axis) x 2 (minor_axis)
Items axis: A to D
Major_axis axis: 2013-01-01 00:00:00 to 2013-01-03 00:00:00
Minor_axis axis: first to second

In [56]:
p[:, :, "second"]

A   B   C   D
2013-01-01  1   7  13  19
2013-01-02  3   9  15  21
2013-01-03  5  11  17  23

In [57]:
p[:, :, "first"]

A   B   C   D
2013-01-01  0   6  12  18
2013-01-02  2   8  14  20
2013-01-03  4  10  16  22

In [58]:
p["A", :, :]

first  second
2013-01-01      0       1
2013-01-02      2       3
2013-01-03      4       5